#!/bin/bash


        echo "                =========================================================================                         "
        echo "             =======            >>> PLATFORM STATUS DASHBOARD tool 2.0 <<<            ======                      "
        echo "        -====                                                                               ====-                 "
        echo "   ---====    - https://confluence.intgdc.com/display/PSM/Platform+Status+Monitoring+Home      ====---            "
        echo "         -==   - Documentation: https://confluence.intgdc.com/display/support/Monitoring      ==-                 "
        echo "           ------========================================================================------                   "
        echo "                  -h, -help, -H  Help  ...  Shows help                                                            "
        echo "                  -s ... ... --- ... ... -  Setups credentials and confluence properties                          "
        echo "                  -D ... ... --- ... ... -  Deletes credentials and confluence properties                         "
        echo "                                                                                                                  "
        echo "                  -Wizz  ... ... --- ... .. runs Wizzard   "
        echo "                                                                                                                  "
        echo "                  -wod  ... ... --- ... ..  Watch on Duty - changes state of Platform Watch to ONLINE   "
        echo "                  -wood ... --- ... ... --- Watch out of duty - changes state of Platform Watch to OFFLINE  "
        echo "                                                                                                                  "
        echo "                  -grey  ... ... --- ... ..  Watch out of duty + everything grey "
        echo "                  -green  ... ... --- ... .. Watch on duty + everything green "
        echo "                                                                                                                  "
        echo "                  -list . --- ... ... --- . Gives values which could be usd within some scripts                  "
        echo "                                                                                                                  "
        echo "           - Please, see help for more informations.                                                              "
        echo "    >>> ---=====================......................................=========================--- <<<            "
        echo "                                      + By ZMA for Good people +                                                  "
        echo "                                                                                                                  "
        echo "                   *********        GoodData | gooddata.com            ***********                                "
        echo "                        *****       Karolínská 650/1, Danube House   *****                                        "
        echo "                           *****    Prague, Czech republic        *****                                           "
        echo "                                                                                                                  "
        echo "                                  +++ Monetize your data +++                                                      "
        echo "                                                                                                                  "
        echo "Enjoy ........                                                                                                    "
        echo "                                                                                                                  "
